backend:
  name: github
  repo: GhostRicity/retro-back
  branch: master

  use_graphql: true

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - label: Blog
    name: blog
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - {
          name: thumbnail,
          label: Featured Image,
          widget: image,
          required: false,
        }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
